apiVersion: v1
kind: persistent volume
metadata:
  name: ebs-static
spec: 
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
   driver: ebs.csi.aws.com
   fsType: ext4
   VolumeHandle: vol-072a8f44214a23f64  ##give the volume on ec2-instance-node(20-gb)


##git add. ; git commit -m "ebs" ; git push origin main
##cd k8-resource/volumes
##kubectl apply -f 01-ebs-static.yml
##kubectl get pv --> see the volume.



###pvc - peersisitent volume claim
##pvc--> it is claiming resource of the storage i.e pv
#you can create the lables to the nodes,use those labels as node selectors inside pod.

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi


##git add. ; git commit -m "ebs" ; git push origin main
##cd k8-resource/volumes
##kubectl apply -f 01-ebs-static.yml
##kubectl get pv --> see the volume.
##kubectl get pvc --> see the pvc volume

##kubectl describe pv ebs-static
##kubectl describe pvc ebs-static


## next we can add the pvc in pod.

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-static-demo
    project: roboshop
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # docker run -v host-path:container-path
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static

##git add. ; git commit -m "ebs" ; git push origin main
##cd k8-resource/volumes
##kubectl apply -f 01-ebs-static.yml

#kubectl get pods -o wide

---
apiVersion: v1
kind: Service
metadata:
  name: ebs-static
  labels:
    purpose: ebs-static-demo
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port

##git add. ; git commit -m "ebs" ; git push origin main
##cd k8-resource/volumes
##kubectl apply -f 01-ebs-static.yml
##kubectl get svc

   