apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: roboshop-ebs
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-dynamic-demo
    project: roboshop
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # docker run -v host-path:container-path
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic


##git add . ; git commit -m "sc" ; git push origin main
##git pull
##k8-resource/volumes/kubectl apply -f 02--sc.yml
##kubectl get sc
##kubectl apply -f 03-ebs-dynamic.yml
##kubectl get pods
##aws console and check the volumes.disk willbe created automatically.
##kubectl get pv --> whenever disk created automatically PV created.