apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: roboshop
    instanceTypes: ["t3.small"]
    desiredCapacity: 3
    minSize: 3
    maxSize: 4

