[local]
localhost


[frontend]
54.226.2.130 COURSE=Ansible DURATION=10hr TRAINER=Satyam ansible_user=ec2-user ansible_password=DevOps321
3.88.235.55 COURSE=Variables DURATION=1.5 hr TRAINER=Satym ansible_user=ec2-user ansible_password=DevOps321

; [local:vars]
; COURSE=Ansible
; TRAINER=Satyam
; DURATION=1.5Hr

