[local]
localhost


[frontend]
3.80.143.15
; 172.31.17.230 COURSE=Ansible DURATION=10hr TRAINER=Satyam ansible_user=ec2-user ansible_password=DevOps321
; 172.31.19.161 COURSE=Variables DURATION=1.5hr TRAINER=Satym ansible_user=ec2-user ansible_password=DevOps321

[local:vars]
COURSE=Ansible
TRAINER=Satyam
DURATION=1.5Hr
GREETING="Hello from Inventory"