
pipeline {
    agent {
        label 'AGENT-1'
    }

    environment {
            appVersion = '' ## give empty after we provide in run time
        }

    stages {

        stage('Build') {
            steps {
                script {
                    echo "building ..."

                    sh """
                        echo "Hello Build"
                        echo "Course: \$COURSE"
                    """

                    echo 'Building the application'
                }
            }
        }

        stage('Read pacjage.json') {
            steps {
                script {
                  def packageJson = readJSON file: 'package.json'
                  appVersion = packageJson.appVersion
                  echo "Package Version: ${appVersion}"
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    echo 'testing ...'
                }

                echo 'Testing the application'
            }
        }

        stage('Deploy') {
            steps {
                script {
                    echo 'deploying ...'
                }

                echo 'Deploying the application'
            }
        }
    }

    post {
        always {
            echo 'I will always say Hello again!'
            deleteDir()
        }

        success {
            echo 'Hello Success'
        }

        failure {
            echo 'Hello Failure'
        }
    }
}
